/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2014 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.ButtonRenderer");sap.m.ButtonRenderer={};
sap.m.ButtonRenderer.render=function(r,b){if(!b.getVisible()){return}var t=b.getType();var e=b.getEnabled();var w=b.getWidth();var T=b.getTooltip_AsString();var B=sap.ui.core.IconPool.getIconURI("nav-back");r.write("<button type=\"button\"");r.writeControlData(b);if(t!==sap.m.ButtonType.Unstyled){r.addClass("sapMBtn");r.writeClasses();r.writeAttribute("tabindex","-1");if(w==="100%"){r.addStyle("width",w);r.writeStyles()}}r.write(">");r.write("<div");r.writeAttribute("id",b.getId()+"-inner");if(t!==sap.m.ButtonType.Unstyled){r.addClass("sapMBtnInner")}if(sap.ui.Device.system.desktop){r.addClass("sapMBtnDesktop")}if(!e){r.addClass("sapMBtnDisabled");r.writeAttribute("tabindex","-1")}else if(sap.ui.Device.system.desktop){r.addClass("sapMFocusable");r.writeAttribute("tabindex","0");switch(t){case sap.m.ButtonType.Accept:case sap.m.ButtonType.Reject:case sap.m.ButtonType.Emphasized:r.addClass("sapMBtnInverted")}}if(this.renderButtonAttributes){this.renderButtonAttributes(r,b)}if(!b.getIcon()){if(t!=sap.m.ButtonType.Back&&t!=sap.m.ButtonType.Up){r.addClass("sapMBtnPaddingLeft")}if(b.getText()){r.addClass("sapMBtnPaddingRight")}}else{if(b.getIcon()&&b.getText()&&b.getIconFirst()){r.addClass("sapMBtnPaddingRight")}if(b.getIcon()&&b.getText()&&!b.getIconFirst()){if(t!=sap.m.ButtonType.Back&&t!=sap.m.ButtonType.Up){r.addClass("sapMBtnPaddingLeft")}}}if(t!==sap.m.ButtonType.Unstyled&&t!==""){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t))}r.writeClasses();if(w!=""||w.toLowerCase()==="auto"){r.addStyle("width",w)}r.writeStyles();if(T){r.writeAttributeEscaped("title",T)}r.write(">");if(t===sap.m.ButtonType.Back||t===sap.m.ButtonType.Up){r.write("<div");r.addClass("sapMBtnIcon");if(b.getText()){r.addClass("sapMBtnIconLeft")}r.writeClasses();r.write(">");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Back,B);this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Up,B);r.write("</div>")}if(b.getIcon()){r.write("<div");r.addClass("sapMBtnIcon");if(b.getText()){if(b.getIconFirst()){r.addClass("sapMBtnIconLeft")}else{r.addClass("sapMBtnIconRight")}}r.writeClasses();r.write(">");this.writeImgHtml(r,b);r.write("</div>")}if(b.getText()){r.write("<span");r.addClass("sapMBtnContent");r.writeClasses();r.write(">");r.writeEscaped(b.getText());r.write("</span>")}r.write("</div>");r.write("</button>")};
sap.m.ButtonRenderer.writeImgHtml=function(r,b){r.renderControl(b._getImage((b.getId()+"-img"),b.getIcon(),b.getActiveIcon(),b.getIconDensityAware()))};
sap.m.ButtonRenderer.writeInternalIconPoolHtml=function(r,b,t,c,u){if(t===c){if(b._imageBtn){b._imageBtn.setSrc(u)}else{r.renderControl(b._getInternalIconBtn((b.getId()+"-iconBtn"),u))}}};
